info:
  component: Ibge-Service
server:

  port: 8080
spring:
  http:
    encoding:
      enabled: true
  application:
    name: ibge-service
feign:
  httpclient:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types:
        - application/json
      min-request-size: 2048
    response:
      enabled: true
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: http://127.0.0.1:8080/actuator/info
    healthCheckUrlPath: http://127.0.0.1:8080/actuator/health
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka